apiKey: 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

# Aerospike configuration  
hostName: 127.0.0.1
port: 3000      
namespace: test
setName: emailDetails

logging:
  level: INFO
  loggers:
    com.communication: DEBUG
